# Generated by Django 4.1.4 on 2022-12-31 11:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('ctr', 'Contract'), ('dee', 'Deed'), ('coo', 'C of O')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('PTIN', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('building_use', models.CharField(choices=[('DPX', 'Duplex (Storey Building)'), ('ffy', 'Face me/Face you (Rooming System)'), ('bgw', 'Bungalow'), ('mfr', 'Multiple Family Residency')], default='bgw', max_length=3)),
                ('plot_length', models.IntegerField()),
                ('plot_width', models.IntegerField()),
                ('plot_area', models.IntegerField()),
                ('number_of_floor', models.IntegerField()),
                ('number_of_rooms', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('year_of_construction', models.IntegerField()),
                ('condition', models.CharField(choices=[('good', 'Good'), ('reqr', 'Requires Renovation')], max_length=4)),
                ('water_source', models.CharField(choices=[('peb', 'Personal Borehole'), ('pub', 'Public Borehole'), ('put', 'Public Tap'), ('wel', 'Well')], max_length=3)),
                ('has_electricity', models.BooleanField(default=True)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo4', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo5', models.ImageField(blank=True, null=True, upload_to='')),
                ('tax_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('title', models.ManyToManyField(to='buildings.title')),
            ],
        ),
    ]
