# Generated by Django 4.1.4 on 2023-01-07 22:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptin', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('building_type', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_area', models.CharField(blank=True, max_length=50, null=True)),
                ('no_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('no_rooms', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
                ('year_no', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('water_source', models.CharField(blank=True, max_length=50, null=True)),
                ('has_electricity', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo1', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo2', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo3', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo4', models.ImageField(blank=True, null=True, upload_to='')),
                ('building_photo5', models.ImageField(blank=True, null=True, upload_to='')),
                ('tax_due', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('tax_paid', models.DecimalField(blank=True, decimal_places=3, max_digits=50, null=True)),
                ('city_name', models.CharField(blank=True, max_length=50, null=True)),
                ('taxable', models.CharField(blank=True, max_length=50, null=True)),
                ('Street_Na', models.CharField(blank=True, max_length=50, null=True)),
                ('construction_material', models.CharField(blank=True, max_length=50, null=True)),
                ('number_buildings', models.CharField(blank=True, max_length=50, null=True)),
                ('Buildi_Fin', models.CharField(blank=True, max_length=50, null=True)),
                ('plot_size', models.CharField(blank=True, max_length=50, null=True)),
                ('poly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
